### ISSUE TITLE
[BUG] Number format exception with custom formatting

### ISSUE THREAD

**Issue by kohle** [PluginBugs/Issues-RPGMoney#12]
**Describe the bug**
Changing the `lore-amount` in the config to add a `$` throws a number format exception when the player attempts to redeem the money received from `/rm get`.

**To Reproduce**
1. Edit `lore-amount` in the `language.yml` file to include `$` (in my case I have it set to `lore-amount: '&aValue: &6&l$'`)
2. Use the `/rm get` command in game
3. Attempt to redeem (both with the hot key and/or right click)

**Expected behavior**
It should redeem the value. Another option might be using the `currency-format` field, but I don't mind having to set it manually in the separate option.

**Info (please complete the following information):**
 - Server version: git-Paper-266 (MC: 1.17.1)
 - Client version: Vanilla 1.17.1
 - Plugin version: 1.1.30

**Additional context**
Console error log:
`Could not pass event PlayerInteractEvent to RPGMoney v1.1.30
java.lang.NumberFormatException: For input string: "Value: $1"
        at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
        at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:556) ~[?:?]
        at com.evill4mer.RealMoney.c.b.a(SourceFile:139) ~[RPGMoney.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor226.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-266]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:542) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:500) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:496) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1862) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-266]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by kohle** [comment]
A separate suggestion, but it would be great if admins could generate the physical money without needing to have their own balance. Maybe something like `/rm adminget <amount>`? Optional argument for multiple would be awesome too! Like `/rm get 1 64` would give you 64 items each worth $1.

**Comment by LoneDev6** [comment]
Thanks, I'll post an update to day with the `lore-amount: '&aValue: &6&l$'` fix.

> A separate suggestion, but it would be great if admins could generate the physical money without needing to have their own balance

I'll add a permission `rpgmoney.get.nowithdraw` which will avoid the admin to see the amount taken from their account when using the command, it makes sense since admins may need this to create shops with trades for example.


>Optional argument for multiple would be awesome too

You can already achieve this by using `/more` command of essentials and similar plugins to max the stack size to 64 of the item you are holding.


Have a nice day

**Comment by kohle** [comment]
Works great, thank you! I didn't know about the `/more` command with Essentials, great solution.

**Comment by LoneDev6** [comment]
No problem!
Have fun :D and good luck with your projects
