### ISSUE TITLE
Could not pass event EntityDeathEvent to RPGMoney v1.1.32

### ISSUE THREAD

**Issue by maxedrom** [PluginBugs/Issues-RPGMoney#30]
I have ittemsadder, and i installed RPGMONEY in a 1.19.2 Server (paper)
I set the config of RPGMONEY like this, as it said on the wiki: https://itemsadder.devs.beer/compatibility-with-other-plugins/compatible/rpgmoney

I have to add that i have the resource pack that include the coin icon.

Well into the game, never drop a coin, and in the console, this message appear:

[19:03:10 ERROR]: Could not pass event EntityDeathEvent to RPGMoney v1.1.32
j**ava.lang.IllegalArgumentException: No enum constant dev.lone.LoneLibs.Mat.itemsadder:coin**
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at dev.lone.LoneLibs.Mat.valueOf(Mat.java:31) ~[LoneLibs.jar:?]
        at com.evill4mer.RealMoney.RealMoney.a(SourceFile:648) ~[RPGMoney.jar:?]
        at com.evill4mer.RealMoney.RealMoney.b(SourceFile:665) ~[RPGMoney.jar:?]
        at com.evill4mer.RealMoney.RealMoney.a(SourceFile:684) ~[RPGMoney.jar:?]
        at com.evill4mer.RealMoney.RealMoney.b(SourceFile:562) ~[RPGMoney.jar:?]
        at com.evill4mer.RealMoney.c.b.a(SourceFile:280) ~[RPGMoney.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor690.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-132]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at gcspawners.EntityDamageHandler.parseDamage(EntityDamageHandler.java:137) ~[AdvancedSpawners-3.8.0.jar:?]
        at gcspawners.EntityDamageHandler.onNaturalDamage(EntityDamageHandler.java:175) ~[AdvancedSpawners-3.8.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-132]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]

**Comment by LoneDev6** [comment]
This happens if ItemsAdder is not loaded or failed to load.
I cannot assume anything else because I cannot see your complete log.

Anyway in the next update the plugin won't stop loading even if this error occurs and will warn you about it.
