### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by StephenGFX** [PluginBugs/Issues-RPGMoney#39]
The plugin doesn't seem to work in 1.20.1, it does load, but generates an error in the console on entity's death, could please fix it ?

Console Error
```
[ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.1.32-r2
dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: [?]Error while calling the method 'putString(java.lang.String,java.lang.String)', loaded: true, Enum: COMPOUND_SET_STRING, Passed Class: class java.lang.Boolean
at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[LoneLibs.jar:?]
at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:615) ~[LoneLibs.jar:?]
at dev.lone.LoneLibs.nbt.nbtapi.NBTCompound.setString(NBTCompound.java:115) ~[LoneLibs.jar:?]
at dev.lone.rpgmoney.RpgMoney.b(SourceFile:642) ~[RPGMoney_1.1.32-r2.jar:?]
at dev.lone.rpgmoney.RpgMoney.a(SourceFile:595) ~[RPGMoney_1.1.32-r2.jar:?]
at dev.lone.rpgmoney.RpgMoney.c(SourceFile:654) ~[RPGMoney_1.1.32-r2.jar:?]
at dev.lone.rpgmoney.RpgMoney.a(SourceFile:670) ~[RPGMoney_1.1.32-r2.jar:?]
at dev.lone.rpgmoney.RpgMoney.b(SourceFile:456) ~[RPGMoney_1.1.32-r2.jar:?]
at dev.lone.rpgmoney.b.b.a(SourceFile:252) ~[RPGMoney_1.1.32-r2.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor458.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-45]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-45]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-45]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:894) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1811) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1705) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1529) ~[?:?]
at net.minecraft.world.entity.player.Player.attack(Player.java:1320) ~[?:?]
at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2875) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2799) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-45]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[LoneLibs.jar:?]
... 41 more
```

Info:
 - Server version:  paper 1.20.1
 - Plugin version: latest

**Comment by LoneDev6** [comment]
Update LoneLibs, are you using the latest version 1.0.25?
https://www.spigotmc.org/resources/lonelibs.75974/
