### ISSUE TITLE
Could not pass event EntityDeathEvent to RPGMoney v1.2.0

### ISSUE THREAD

**Issue by BronzWarq** [PluginBugs/Issues-RPGMoney#43]
**Describe the bug**
When loading a map on the server, an error appears in the console  https://paste.helpch.at/royojilaxa.rb

**To Reproduce**
When loading a map on the server

```
[20:12:18 ERROR]: Could not pass event EntityDeathEvent to RPGMoney v1.2.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
        at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
        at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
        at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
        at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[ssspigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[ssspigot-api-1.20.2-R0.1-SNAPSHOT.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:621) ~[ssspigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:961) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1847) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1741) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1564) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.hurt(Animal.java:87) ~[?:?]
        at net.minecraft.world.entity.animal.horse.AbstractHorse.hurt(AbstractHorse.java:391) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:420) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:369) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:824) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3028) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:442) ~[?:?]
        at net.minecraft.world.entity.animal.horse.AbstractHorse.tick(AbstractHorse.java:641) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tickNonPassengerAsync$17(ServerLevel.java:1461) ~[?:?]
        at net.minecraft.server.TickServ.lambda$entityPack$2(TickServ.java:100) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.server.TickServ.flush(TickServ.java:228) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1440) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[ssspigot-1.20.2.jar:SSSpigot2-1.20.2-20231112-7b0a3bc]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Info (please complete the following information):**
 - Server version: 1.20.2
 - Client version: 1.202.
 - Plugin version: 1.2.0

**Comment by StephenGFX** [comment]
Hey I got a similar issue : 
```
[22:38:30]
[ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.2.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-393]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-393]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-393]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1837) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1731) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:417) ~[?:?]
at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
at net.minecraft.world.entity.Entity.tick(Entity.java:811) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3003) ~[?:?]
at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
at net.minecraft.world.entity.monster.Skeleton.tick(Skeleton.java:69) ~[?:?]
at net.minecraft.world.entity.Entity.rideTick(Entity.java:2859) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.rideTick(LivingEntity.java:3653) ~[?:?]
at net.minecraft.world.entity.monster.AbstractSkeleton.rideTick(AbstractSkeleton.java:136) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickPassenger(ServerLevel.java:1454) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1424) ~[?:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:1319) ~[?:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:921) ~[?:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1711) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-393]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:40:35]
[WARN] Stephen_GFX moved too quickly! 4.716729597157382,0.0,9.512284307160826
[22:41:52]
[ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.2.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-393]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-393]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-393]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1837) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1731) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:211) ~[?:?]
at net.minecraft.world.entity.Entity.baseTick(Entity.java:858) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:406) ~[?:?]
at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
at net.minecraft.world.entity.Entity.tick(Entity.java:811) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3003) ~[?:?]
at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:124) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1414) ~[?:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:1319) ~[?:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:921) ~[?:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1711) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-393]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:43:30]
[ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.2.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-393]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-393]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-393]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1837) ~[?:?]
at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1731) ~[?:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.hurt(Bat.java:211) ~[?:?]
at net.minecraft.world.entity.Entity.baseTick(Entity.java:858) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:406) ~[?:?]
at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
at net.minecraft.world.entity.Entity.tick(Entity.java:811) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3003) ~[?:?]
at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:124) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1414) ~[?:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:1319) ~[?:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:921) ~[?:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1711) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-393]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-393]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:43:56]
[WARN] Stephen_GFX moved too quickly! -3.51513859860961,2.036105825723311,9.998062973788592
```

**Comment by BronzWarq** [comment]
plz update plugin =\

**Comment by Nahalyd** [comment]
Title
After killing a mob, there is often a large error message in the console.

How to Reproduce
- When a mob kills itself without an agressor (suicide, lava, ...).
- Not when a zombie is converted in water


What happened
This message appears
```
[22:23:19] [Server thread/ERROR]: Could not pass event EntityDeathEvent to RPGMoney v1.2.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
	at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
	at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
	at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
	at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-390]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-390]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-390]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1837) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1731) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:858) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:406) ~[?:?]
	at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:811) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3003) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:240) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1414) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1319) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:921) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1711) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-390]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-390]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

What should have happened:
No error

System Info:
    Server version: Paper 1.20.4
    Client version: 1.20.4
    Plugin version: 1.2.0

**Comment by Nahalyd** [comment]
> Title After killing a mob, there is often a large error message in the console.
> 
> How to Reproduce
> 
>     * When a mob kills itself without an agressor (suicide, lava, ...).
> 
>     * Not when a zombie is converted in water
> 
> 
> What happened This message appears
> 
> ```
> [22:23:19] [Server thread/ERROR]: Could not pass event EntityDeathEvent to RPGMoney v1.2.0
> java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getUniqueId()" because "<parameter1>" is null
> 	at dev.lone.rpgmoney.h.a(SourceFile:24) ~[RPGMoney_1.2.0.jar:?]
> 	at dev.lone.rpgmoney.h.a(SourceFile:51) ~[RPGMoney_1.2.0.jar:?]
> 	at dev.lone.rpgmoney.g.b(SourceFile:46) ~[RPGMoney_1.2.0.jar:?]
> 	at dev.lone.rpgmoney.aa.a(SourceFile:282) ~[RPGMoney_1.2.0.jar:?]
> 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-390]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-390]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-390]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:959) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1837) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1731) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
> 	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
> 	at net.minecraft.world.entity.Entity.baseTick(Entity.java:858) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:406) ~[?:?]
> 	at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
> 	at net.minecraft.world.entity.Entity.tick(Entity.java:811) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3003) ~[?:?]
> 	at net.minecraft.world.entity.Mob.tick(Mob.java:437) ~[?:?]
> 	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:240) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1414) ~[?:?]
> 	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1319) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:921) ~[?:?]
> 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1711) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1512) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-390]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-390]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> What should have happened: No error
> 
> System Info: Server version: Paper 1.20.4 Client version: 1.20.4 Plugin version: 1.2.0

I've done some tests. It's just a null case management to apply when the mobs die alone.
The spamming impression is due to day light on zombies and skeletons.
